apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: mjbae327/gateway:latest
          env:
            - name: api.url.order
              value: "http://order:8080"
            - name: api.url.menu
              value: "http://menu:8080"
            - name: api.url.store
              value: "http://store:8080"
            - name: api.url.inventory
              value: "http://inventory:8080"
          ports:
            - containerPort: 8080
